# Define default image
image: "alpine/python:latest"
defaults:
  variables:
    RUN_ENVIRONMENT: "testapi"
    RUN_DIRECTION: "dest"
    RUN_CONFIG: "config.ini"
    PATH_CI_TEMPLATES: "ci-templates/gitlab"

##
# Define the pipeline stages
##
stages:
  # Run linters, unit tests etc.
  - test
  # Create a release from a git tag
  - release
  # Build packages for release
  - build
  # Deploy packages to package registries
  - deploy
  # Run the hcloud-reassign script in a pipeline
  - run


# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
sast:
  stage: test

# Include jobs and templates
include:
  - local: "ci-templates/gitlab/jobs_test.yml"
  - local: "ci-templates/gitlab/jobs_release.yml"
  - local: "ci-templates/gitlab/jobs_build.yml"
  - local: "ci-templates/gitlab/jobs_deploy.yml"
  - local: "ci-templates/gitlab/jobs_run.yml"
  - template: "Security/SAST.gitlab-ci.yml"
