[build-system]
requires = [
  "setuptools >= 40.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "hcloud_reassign"
dynamic = ["version"]
requires-python = ">= 3.11"
dependencies = [
    "hcloud>=2.3.0",
]
